### PR TITLE
Dashboard for showing k8s log ingest breakdown

### PR DESCRIPTION
**Pull request by JimHagan**
This dashboard gives a few simple visualizations that tell a customer which log sources are contributing the most to log ingest.  It uses the NRQL operator `bytecountestimate()`.

Currently it has four pie charts faceted on:

- app
- environment
- container

### CODE REVIEW

**Comment by JimHagan** [comment]
@bmbost This is the dashboard template pull request for log ingest breakdown.

**Comment by kidk** [comment]
Hi @JimHagan Thanks a lot for adding this. I saw you made some more changes, is this now ready to review?

**Comment by JimHagan** [comment]
> Hi @JimHagan Thanks a lot for adding this. I saw you made some more changes, is this now ready to review?

**Comment by JimHagan** [comment]
@kidk This should be ready to review

**Comment by kidk** [comment]
Thanks @JimHagan 🎆

**Pull request merged**
